name: whatsapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  lottie: ^3.3.1
  modal_progress_hud_nsn: ^0.5.1
  device_preview: ^1.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.3
  pin_code_fields: ^8.0.1
  socket_io_client: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic  

flutter_assets:
  assets_path: assets/svg
  output_path: lib/core/utils
  filename: app_svgs.dart
  field_prefix: null
  classname: AppSvgs
# flutter_assets:
#   assets_path: assets/images
#   output_path: lib/core/utils
#   filename: app_images.dart
#   field_prefix: null
#   classname: AppImages

# flutter_assets:
#   assets_path: assets/animations
#   output_path: lib/core/utils
#   filename: app_animations.dart
#   field_prefix: null
#   classname: AppAnimations
